info:
  contact: {}
paths:
  /greet/:
    get:
      consumes:
      - '*/*'
      description: get title by name
      parameters:
      - description: Some Name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Greet name
swagger: "2.0"
